#pragma once
void test_append();
void test_prepend();
void test_insertAt();
void test_concat();
void test_remove();
void test_popFirst();
void test_popLast();
void test_UniquePtr();
void test_SharedPtr();
void test_WeakPtr();